default: &default
  encoding: utf8
  pool: 5
  
development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: postgresql
  username: postgres
  database: cwr_<%= Rails.env %>

production:
  <<: *default
  adapter: postgresql
  database: cwr_<%= Rails.env %>
  password: